// <auto-generated />
using System;
using CozyComfort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozyComfort.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708044025_AddCustomerOrders")]
    partial class AddCustomerOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CozyComfort.Domain.Entities.BlanketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("BlanketModels");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("CustomerOrders", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerOrders_FinalSource", "FinalSource IS NULL OR FinalSource IN\r\n            (\r\n            'SellerStock',\r\n            'DistributorStock',\r\n            'FactoryStock',\r\n            'FactoryProduction'\r\n            )");

                            t.HasCheckConstraint("CK_CustomerOrders_Status", "Status IN \r\n            (\r\n            'Pending',\r\n            'CheckingSellerStock',\r\n            'CheckingDistributorStock',\r\n            'CheckingFactoryStock',\r\n            'WaitingProduction',\r\n            'Confirmed',\r\n            'InFulfillment',\r\n            'Dispatched',\r\n            'Delivered',\r\n            'Cancelled'\r\n            )");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.DistributorInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[QuantityOnHand]-[ReservedQuantity]", true);

                    b.Property<int>("BlanketModelId")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BlanketModelId");

                    b.HasIndex("DistributorId", "BlanketModelId")
                        .IsUnique();

                    b.ToTable("DistributorInventories", t =>
                        {
                            t.HasCheckConstraint("CK_DistributorInventories_Qty", "[QuantityOnHand] >= 0 AND [ReservedQuantity] >= 0 AND [ReservedQuantity] <= [QuantityOnHand]");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.FactoryInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[QuantityOnHand]-[ReservedQuantity]", true);

                    b.Property<int>("BlanketModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BlanketModelId")
                        .IsUnique();

                    b.ToTable("FactoryInventories", t =>
                        {
                            t.HasCheckConstraint("CK_FactoryInventories_Qty", "[QuantityOnHand] >= 0 AND [ReservedQuantity] >= 0 AND [ReservedQuantity] <= [QuantityOnHand]");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialName")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.ProductionCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlanketModelId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPendingQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DailyCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlanketModelId")
                        .IsUnique();

                    b.ToTable("ProductionCapacities", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionCapacities_Values", "DailyCapacity >= 0\r\n            AND WeeklyCapacity >= 0\r\n            AND CurrentPendingQuantity >= 0\r\n            AND LeadTimeDays >= 0");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StoreType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("Sellers", t =>
                        {
                            t.HasCheckConstraint("CK_Sellers_StoreType", "[StoreType] IN ('Online','Physical','Hybrid')");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.SellerInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[QuantityOnHand]-[ReservedQuantity]", true);

                    b.Property<int>("BlanketModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("QuantityOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlanketModelId");

                    b.HasIndex("SellerId", "BlanketModelId")
                        .IsUnique();

                    b.ToTable("SellerInventories", t =>
                        {
                            t.HasCheckConstraint("CK_SellerInventories_Qty", "[QuantityOnHand] >= 0 AND [ReservedQuantity] >= 0 AND [ReservedQuantity] <= [QuantityOnHand]");
                        });
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.BlanketModel", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.Material", "Material")
                        .WithMany("BlanketModels")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.CustomerOrder", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CozyComfort.Domain.Entities.Seller", "Seller")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.DistributorInventory", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.BlanketModel", "BlanketModel")
                        .WithMany("DistributorInventories")
                        .HasForeignKey("BlanketModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CozyComfort.Domain.Entities.Distributor", "Distributor")
                        .WithMany("DistributorInventories")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlanketModel");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.FactoryInventory", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.BlanketModel", "BlanketModel")
                        .WithMany("FactoryInventories")
                        .HasForeignKey("BlanketModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlanketModel");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.ProductionCapacity", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.BlanketModel", "BlanketModel")
                        .WithMany("ProductionCapacities")
                        .HasForeignKey("BlanketModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlanketModel");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Seller", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.Distributor", "Distributor")
                        .WithMany("Sellers")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.SellerInventory", b =>
                {
                    b.HasOne("CozyComfort.Domain.Entities.BlanketModel", "BlanketModel")
                        .WithMany("SellerInventories")
                        .HasForeignKey("BlanketModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CozyComfort.Domain.Entities.Seller", "Seller")
                        .WithMany("SellerInventories")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlanketModel");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.BlanketModel", b =>
                {
                    b.Navigation("DistributorInventories");

                    b.Navigation("FactoryInventories");

                    b.Navigation("ProductionCapacities");

                    b.Navigation("SellerInventories");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Distributor", b =>
                {
                    b.Navigation("DistributorInventories");

                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Material", b =>
                {
                    b.Navigation("BlanketModels");
                });

            modelBuilder.Entity("CozyComfort.Domain.Entities.Seller", b =>
                {
                    b.Navigation("CustomerOrders");

                    b.Navigation("SellerInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
