<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CozyComfort.Domain\CozyComfort.Domain.csproj" />
    <ProjectReference Include="..\CozyComfort.Infrastucture\CozyComfort.Infrastucture.csproj" />
  </ItemGroup>

</Project>
